export const KeyAliases = {
	// TODO: needed?
	F1: 'F1',
	F2: 'F2',
	F3: 'F3',
	F4: 'F4',
	F5: 'F5',
	F6: 'F6',
	F7: 'F7',
	F8: 'F8',
	F9: 'F9',
	F10: 'F10',
	F11: 'F11',
	F12: 'F12',

	'1': 'Digit1',
	DIGIT1: 'Digit1',
	'2': 'Digit2',
	DIGIT2: 'Digit2',
	'3': 'Digit3',
	DIGIT3: 'Digit3',
	'4': 'Digit4',
	DIGIT4: 'Digit4',
	'5': 'Digit5',
	DIGIT5: 'Digit5',
	'6': 'Digit6',
	DIGIT6: 'Digit6',
	'7': 'Digit7',
	DIGIT7: 'Digit7',
	'8': 'Digit8',
	DIGIT8: 'Digit8',
	'9': 'Digit9',
	DIGIT9: 'Digit9',
	'0': 'Digit0',
	DIGIT0: 'Digit0',

	MINUS: 'Minus',
	PLUS: 'Equal',
	EQUAL: 'Equal',

	A: 'KeyA',
	B: 'KeyB',
	C: 'KeyC',
	D: 'KeyD',
	E: 'KeyE',
	G: 'KeyG',
	H: 'KeyH',
	I: 'KeyI',
	J: 'KeyJ',
	K: 'KeyK',
	L: 'KeyL',
	M: 'KeyM',
	N: 'KeyN',
	O: 'KeyO',
	P: 'KeyP',
	Q: 'KeyQ',
	R: 'KeyR',
	S: 'KeyS',
	T: 'KeyT',
	U: 'KeyU',
	V: 'KeyV',
	W: 'KeyW',
	X: 'KeyX',
	Y: 'KeyY',
	Z: 'KeyZ',

	BACKQUOTE: 'Backquote',
	SLASH: 'Slash',
	BACKSLASH: 'Backslash',
	QUOTE: 'Quote',
	SEMICOLON: 'Semicolon',
	PERIOD: 'Period',
	COMMA: 'Comma',
	'>': 'Period',
	'<': 'Comma',
	BRACKETRIGHT: 'BracketRight',
	BRACKETLEFT: 'BracketLeft',
	']': 'BracketRight',
	'}': 'BracketRight',
	'[': 'BracketLeft',
	'{': 'BracketLeft',

	ENTER: 'Enter',
	SPACE: 'Space',
	BACKSPACE: 'Backspace',
	ESCAPE: 'Escape',
	CAPSLOCK: 'CapsLock',
	TAB: 'Tab',

	CONTROL: 'Control',    // ev.key
	CTRL: 'Control',       // ev.key
	LCTRL: 'ControlLeft',
	RCTRL: 'ControlRight',
	ALT: 'Alt',            // ev.key
	LALT: 'AltLeft',
	RALT: 'AltRight',
	SHIFT: 'Shift',        // ev.key
	LSHIFT: 'ShiftLeft',
	RSHIFT: 'ShiftRight',
	META: 'Meta',          // ev.key
	LMETA: 'MetaLeft',
	RMETA: 'MetaRight',
	CONTEXTMENU: 'ContextMenu',

	PAUSE: 'Pause',
	PAGEUP: 'PageUp',
	PGUP: 'PageUp',
	PAGEDOWN: 'PageDown',
	PGDOWN: 'PageDown',
	HOME: 'Home',
	END: 'End',
	INSERT: 'Insert',
	DELETE: 'Delete',
	UP: 'ArrowUp',
	RIGHT: 'ArrowRight',
	DOWN: 'ArrowDown',
	LEFT: 'ArrowLeft',

	/*
		With 'NumLock' off NUMPAD 0-9 and Decimal have no KeyPress
		Also ev.code is the same but ev.key is: 1=end, 2=arrowDwn, 3=pgDwn etc.
	*/
	NUMLOCK: 'NumLock',
	NUMPAD0: 'Numpad0',
	NUMPAD1: 'Numpad1',
	NUMPAD2: 'Numpad2',
	NUMPAD3: 'Numpad3',
	NUMPAD4: 'Numpad4',
	NUMPAD5: 'Numpad5',
	NUMPAD6: 'Numpad6',
	NUMPAD7: 'Numpad7',
	NUMPAD8: 'Numpad8',
	NUMPAD9: 'Numpad9',
	NUMPADDECIMAL: 'NumpadDecimal',
	NUMPADMULTIPLY: 'NumpadMultiply',
	NUMPADDIVIDE: 'NumpadDivide',
	NUMPADADD: 'NumpadAdd',
	NUMPADSUBTRACT: 'NumpadSubtract',
	NUMPADENTER: 'NumpadEnter',
} as const;
